### ISSUE TITLE
Figure Out the details about persisting data when using docker container

### ISSUE THREAD

**Issue by RomanKrajewski** [vi-sense/vi-sense#13]
- [x] make the database persistent on the htw server
- [x] store the 3d models in the file system of the htw server and make them accessable to the go container

**Comment by dephiloper** [comment]
### Research on multiple database types
#### mysql
docker container: https://hub.docker.com/_/mysql
go-driver: https://github.com/go-sql-driver/mysql
go-orm: https://github.com/jinzhu/gorm

#### postgresql
docker container: https://hub.docker.com/_/postgres
go-driver: https://github.com/lib/pq
go-orm: https://github.com/go-pg/pg

#### mongodb
docker container: https://hub.docker.com/_/mongo
go-driver: https://github.com/mongodb/mongo-go-driver
go-orm: https://github.com/go-bongo/bongo **(unstable)** also probably not needed

#### redis
docker container: https://hub.docker.com/_/redis/
go-client: https://github.com/go-redis/redis
