### ISSUE TITLE
Install Docker on HTW Server

### ISSUE THREAD

**Issue by RomanKrajewski** [vi-sense/vi-sense#15]
- install docker with apt-get or something like that
- enable starting the docker deamon on startup:
      sudo systemctl enable docker

**Comment by dephiloper** [comment]
Installed docker through this guide: https://docs.docker.com/engine/install/debian/#install-using-the-repository#install-from-a-package#install-using-the-repository

**Comment by dephiloper** [comment]
Enabled docker daemon on startup with systemctl:
$ sudo systemctl enable|disable|satus|start|stop docker

https://docs.docker.com/engine/install/linux-postinstall/#configure-docker-to-start-on-boot
