### ISSUE TITLE
Research on rendering and deployment of 3d models using three.js in the browser

### ISSUE THREAD

**Issue by dephiloper** [vi-sense/vi-sense#2]
For a first comparison a project should be created which loads the provided 3d models of metr with three.js. The application needs to be executable in the browser.

Furthermore, the performance of three.js in combination with WebGL should be researched.
Additionally, the availability of techniques such as occlusion culling and plane clipping should be examined.

**Comment by grimmle** [comment]
**Setup**
\+ setup is fairly easy and quick
\+ import of GLTF/GLB models is really easy using the provided GLTFLoader by threejs

**Documentation**
\+ extensive documentation and lots of tutorials/tips online

**Performance**
\+ Firefox & Chrome: good overall performance
\- Safari: performance issues (slight stuttering) when zooming in
\~ 40fps with the smaller models
\~ 15fps with the largest model
\- fps drop significantly the closer you zoom in

**Perfomance optimization**
\+ Clipping Planes and camera frustum culling are implemented and easy to use
\+/- basic occlusion culling seems to implemented as well, dont know how well this works though

![threejs](https://user-images.githubusercontent.com/52577845/79133836-fb2b7e80-7dac-11ea-911d-02ea502ff345.gif)
