### ISSUE TITLE
As a user I want to be able to select a single model to show it in 3d.

### ISSUE THREAD

**Issue by dephiloper** [vi-sense/vi-sense#22]
When the models get selected the necessary data should be downloaded to view it inside the 3d viewer (see https://github.com/vi-sense/vi-sense/issues/19). The user should get indicated that the model is loaded.

**Comment by lnlytumbleweed** [comment]
Plan is:

- [x] Build Babylon app
- [x] Include the app.js in vue in the SPA

**Comment by lnlytumbleweed** [comment]
**Build Babylon app**
@iar5 was building a webpack build for vue (app.js) explained in this issue: https://github.com/vi-sense/vi-sense/issues/37

Handover by constructor variable in Babylon.vue: **model.ID**

Additional var: production for testing (When testing the files can be load locally)

**Comment by lnlytumbleweed** [comment]
**Include the app.js in vue in the SPA**

![Bildschirmfoto 2020-05-06 um 19 35 18](https://user-images.githubusercontent.com/26483797/81210465-3565f580-8fd2-11ea-9e80-52df9beb73a0.png)
![Bildschirmfoto 2020-05-06 um 19 36 33](https://user-images.githubusercontent.com/26483797/81210486-3a2aa980-8fd2-11ea-95e9-54eb2c00b11b.png)

**Comment by lnlytumbleweed** [comment]
improvements: 

- loading bar while loading the gltf from server

- make it as a distinguish page as explained here: https://github.com/vi-sense/vi-sense/issues/40
