### ISSUE TITLE
As a user I want to be able to move and rotate a model in 3d.

### ISSUE THREAD

**Issue by lnlytumbleweed** [vi-sense/vi-sense#23]
Free movement in all directions and rotation around a single sensor.

**Comment by iar5** [comment]
- [ ] Display model after its loaded from the backend
- [ ] (Since a simple movement is already done:) implemented some BIM-specialized, custom controls
- [ ] Center the model

**Comment by iar5** [comment]
Implemented two camera types:
- Arc rotation camera which rotates around a point/sensor
- First person camera locked to XY-axis. With Q/E you can go down/up in the Y-axis ("go one floor down/up in the building")
