### ISSUE TITLE
use string formatter in go

### ISSUE THREAD

**Issue by moethu** [vi-sense/vi-sense#29]
just a quick note, I'd recommend using string formatting with _fmt_
`s := fmt.Sprintf("%s %s", ...)`
https://github.com/vi-sense/vi-sense/blob/9ed93a1a99d4508d6121707fd39c52eb5c4b5177/app/db_handler.go#L226
And test if the line actually has enough fields, what if there is only one char? The parser might fail to so just handle the error with a simple panic, since this is critical for the entire app.

**Comment by dephiloper** [comment]
Sure I will do this. But since this code is just for testing purposes and gets obsolete after we connect the metr api for sensor data it should be not that important.
