### ISSUE TITLE
Research on rendering and deployment of 3d with an alternative framework

### ISSUE THREAD

**Issue by dephiloper** [vi-sense/vi-sense#3]
https://gist.github.com/dmnsgn/76878ba6903cf15789b712464875cfdc

For a first comparison a project should be created which loads the provided 3d models of metr. The application needs to be executable in the browser.

Furthermore, the performance of the selected framework in combination with WebGL should be researched.
Additionally, the availability of techniques such as occlusion culling and plane clipping should be examined.

**Comment by iar5** [comment]
Es gibt eine Vielzahl von 3D Biblitoheken fürs Web. Die meisten scheinen als Hobby entstanden und entwickelt worden zu sein, ohne ein wirkliches Alleinstellungsmerkmal zu haben. 

**Unsere Anforderungen**, soweit ich unser Projekt verstanden habe:
• Hoher Abstraction Layer über WebGL
• Benutzerinteraktion
• Kamerafahrten
• Cliping Plane 
• glTF  Unterstützung
• Gute Dokumentation und aktive Community sind immer gut
• Solide Performance in älterer Browser/Internet Explorer (unbedingt WebGL1 nutzen)
• Effizienz? Lightweight?

**Blend4Web, Verge3D**
• 3D Modelle, Szene etc. in Blender oder 3DMax entwickeln und einfach ins Web portieren
• man macht alles soweit im Editor
\- eher statisch
\- Interaktion/Anbindung an anderes JS schwieriger
\- (Linzenz nötig wenn kommerziell genutzt))

**Scene.js/Xeogl** 
• Scene.js hatte relativ guten Namen soweit ich mich erinnere, wird nun aber für eigenes kommerzielles Projekt verwendet und nicht nicht mehr öffentlich weiterentwickelt
• Nachfolger vom selben Studio: Xeogl
\+ Designed for CAD, **BIM(!!)** and ArchViz
\+ Doku etc. sieht ziemlich gut aus
\- relativ kleine Community 

**Three.js**
\+ sehr weit verbreitet
\+ universell verwendbar, auch viel Schnickschnack und artsy Stuff
\- Oft nicht Persistent zwischen Versionen
\- Module für wzB. für Maussteuerung müssen seperat hinzugefügt werden

**Babylon.js**
• Blender, Maya, 3DS Max Exporter
• jünger als Three.js
• größere Filesize, dafür aber kompakter 
\+ Nach Three.js zweitgrößte Community, die sehr hilfreicher scheint
\+ wird in vielen Vergleichsthreads Three.js bevorzugt, weil es ingesamt stimmiger scheint

____
**Bewertung**
Habe mir ein Minimalbeispiel mit Babylon.js und Xeogl entwickelt, welche unsere glTF Modelle rendern und mit Maus und WASD bedienbar sind. Das Coden ansich war mit Babylon angenehmer,  weil einsteigerfreundlichere Ressourcen. 
Mit Xeogl hatte ich ein Paar Startschwierigkeiten: die Steuerung klappt nicht, wenn ich dem Canvas Element width und height via CSS zuweise. Habe zu meinem Problem nichts im Netz gefunden und musste es durch eigenes Herumprobieren lösen; bei Babylon oder THREE gäbs dazu mit Sicherheit Beiträge von Leuten auf Stackoverflow, die das selbe Problem hatten. 
An Xeogl haben mir die direkt integrierten Kamerafahrten, Steuerung und Annotationen sehr gut gefallen. Der vielleicht wichtigste Punkt: Die Performance spricht klar für Xeogl. Beim größten unserer glTF Modelle schafft Babybon 20 FPS, Xeogl läuft mit flüssigen 60. Hat dafür aber an zwei Stellen Tiefenbuffer Probleme (leichtes flackern). Das ist mir aber nur bei dem einen Modell aufgefallen, scheint also kein allgemeines Problem zu sein. @grimmle wie sieht hier die Performance mit THREE aus?

**Comment by iar5** [comment]
Update Xeogl vs Babylon

**Xeogl**
• https://xeogl.org/examples/#annotations_annotationStory_tronTank
• https://xeogl.org/examples/#importing_gltf_OfficePlan
• https://xeogl.org/examples/#importing_gltf_Schependomlaan
• https://xeogl.org/examples/#camera_path_frameMenu
• scheint Modelle selbstständig zu normalisieren und optimieren
\- ziemlich spannende Beispiele; andererseits existiert schon ewig der Bug dass man die Hintergrundfarbe vom Canvas nicht ändern kann.
\- ~~Problem mit Tiefenbuffer bei Teilmesh beim dritten Modell~~ (entsteht durch Optimierung, selbe Problem hat Babylon auch)

Babylon
\+ 60 FPS sind mit unserem großen Modell laut Forum auch hier möglich
\+ TypeScript Unterstützung
