### ISSUE TITLE
Getting started w/ Go

### ISSUE THREAD

**Issue by dephiloper** [vi-sense/vi-sense#4]
Research on creating projects in go, working with go and deploying applications.

**Comment by RomanKrajewski** [comment]
## Rest API mit Python vs Go ##
### Vorteile von Python: ### 
- mehr libraries
- Komplettpaket mit Django + Django Rest Framework
- habe schon ein bisschen mit Django und relativ viel mit Python gearbeitet
### Vorteile von Go: ###
- Performanter
- Skalierbarerer, dank concurrency features
- man findet viele Artikel wie diesen hier: [Why we switched from Python to Go](https://getstream.io/blog/switched-python-go/) , ich würde es deshalb schon gerne wenigstens mal ausprobieren

Insgesamt ist also Django die wahrscheinlich schneller zu Entwickelnde Lösung und Go die elegantere, schnellere Lösung, die dafür aber etwas mehr Vorbereitung und Einarbeitung erfordert.

**Comment by RomanKrajewski** [comment]
haben uns jetzt für Go entschieden

**Comment by moethu** [comment]
### Some Input on how to build a REST Service in Go
#### Gin-Gonic REST Framework
https://github.com/gin-gonic/gin
https://play.golang.org/p/Y0sDeUcLjv

#### REST Server
https://github.com/moethu/codenutrition/blob/master/main.go#L65
https://github.com/moethu/codenutrition/blob/master/main.go#L136-L145

#### Serving static files
https://github.com/moethu/codenutrition/blob/master/main.go#L61
https://github.com/moethu/codenutrition/blob/master/main.go#L100-L103

#### web sockets
https://github.com/moethu/webg3n/blob/master/main.go
https://github.com/moethu/webg3n/blob/master/server.go

#### JSON Responses
https://github.com/gin-gonic/examples/blob/master/basic/main.go#L22-L30

#### Testing in go
https://github.com/gin-gonic/examples/blob/master/basic/main_test.go

**Comment by moethu** [comment]
#### Go Project Layout
https://github.com/golang-standards/project-layout
#### Go Podcast
https://changelog.com/gotime

**Comment by RomanKrajewski** [comment]
#### from Slack: minimal docker container ####
https://rollout.io/blog/building-minimal-docker-containers-for-go-applications/
#### another article covering that topic ####
https://medium.com/@diogok/on-golang-static-binaries-cross-compiling-and-plugins-1aed33499671

**Comment by RomanKrajewski** [comment]
#### minimal docker image process is also explained in the official docker docs: ####
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
