### ISSUE TITLE
build frontend github action

### ISSUE THREAD

**Issue by dephiloper** [vi-sense/vi-sense#42]

**Comment by RomanKrajewski** [comment]
Implement the building process of the frontend into the cicd pipeline.

**Comment by RomanKrajewski** [comment]
I just implemented a new solution to get the frontend files into the go server image. I tested it and it worked fine, but afterwards i realized that it will probably only work once and it's never gonna include any new frontend code.
After some research i figuered out two suboptimal but clean solutions:
1. Copy the frontend files during the build process of the backend. Disadvantage: the frontend code will only be deployed whenever the backend is deployed
2. Have a seperate frontend server like nginx. Disadvantage: we can't serve our frontend files with go. This would probably be the cleanest solution, as it devides frontend and backend completely.

**Comment by RomanKrajewski** [comment]
we decided to build a small seperate go server for the frontend
