### ISSUE TITLE
create model page

### ISSUE THREAD

**Issue by dephiloper** [vi-sense/vi-sense#43]
additionally, create a model page to the already existing start page
* transform the start page into the model page or redirect

**Comment by lnlytumbleweed** [comment]
First try: Tried with static layout wrapper components and slots. But result not as expected. Clear separation of startpage from modelpage was not good and data binding was not working anymore. Harder then I thought.
Second try: will try with two different layouts (startpage, modelpage) with a dynamic component wrapper as in this approach: https://markus.oberlehner.net/blog/dynamic-vue-layout-components/

**Comment by lnlytumbleweed** [comment]
Third try: complete separation from SPA with separation pages

https://forum.vuejs.org/t/composing-multiple-apps-as-a-single-spa/12622

**Comment by lnlytumbleweed** [comment]
Fourth try: hide previous template is working, but not best practice. Will try second try again.

![Bildschirmfoto 2020-05-12 um 12 18 46](https://user-images.githubusercontent.com/26483797/81677626-679fa900-9451-11ea-97e7-4d623bcd01b9.png)

**Comment by lnlytumbleweed** [comment]
https://router.vuejs.org/guide/essentials/named-views.html#nested-named-views
nested named-views is not working at all.
So the approach with hiding will be the winner for now.
