### ISSUE TITLE
create information pane

### ISSUE THREAD

**Issue by dephiloper** [vi-sense/vi-sense#44]
* expandable list of all sensors (selectable)
* when expanded shows sensor information (name, description, current value, ...)

see https://github.com/vi-sense/vi-sense/issues/40

- [x] Vuetify Implementation
- [x] Sketch the whole Information Pane with all features by now
- [x] Refactor Code
- [x] CSS formatting (@dephiloper: need probably help on this step)
- [ ] TODOs onSensorSelectionChanged & getSelectedSensors in InformationPane.vue

**Comment by lnlytumbleweed** [comment]
needs to be shifted into next sprint

**Comment by lnlytumbleweed** [comment]
**Vuetify Implementation**

Finally on Dev. https://github.com/vi-sense/vi-sense-frontend/commit/5aae532b247d5d07a52e8486fca403ab7c5b697b

![Bildschirmfoto 2020-05-24 um 21 39 29](https://user-images.githubusercontent.com/26483797/82763409-bc570280-9e07-11ea-811e-68e7a800e316.png)

**Comment by lnlytumbleweed** [comment]
**Sketch the whole Information Pane with all features by now:**
Handsketch:
![HandSketch_Infopane_JS](https://user-images.githubusercontent.com/26483797/83351680-7db0d300-a346-11ea-8a19-131ee614fa48.png)

**Comment by lnlytumbleweed** [comment]
**CSS formatting**

![Bildschirmfoto 2020-06-02 um 16 06 29](https://user-images.githubusercontent.com/26483797/83529825-2bf57d80-a4eb-11ea-9cd5-ed044b3dc02f.png)
