### ISSUE TITLE
allow bidrectional communication between babylon and vue

### ISSUE THREAD

**Issue by dephiloper** [vi-sense/vi-sense#45]
* when a sensor is selected in 3d the sensor should also be highlighted in the information pane and vise versa

**Comment by iar5** [comment]
_(in proceeding, just some ideas and notes while thinking about how to solve this the best)_

***Annotation Explanations***
- v means the user action is done in Vue and sent to Babylon
- b means the user action is done in Babylon and sent to Vue

***Requirements, User stories***
- Single source of truth (simple state and getter (e.g. is a sensor selected? when creating a new component))
- Select sensor (v/b)
- Change model appearance (v) in a bunch of ways (based on clicks, options and timeline changes)
- Camera position, flight (v/b)

***Approches***
- API
- Public functions
	- unidirectional but could be ok since v communication is heavier?
- Window events 
	- ez use
	- drawback: no states/getters
- State based wrapper
	- actions, mutations, getters 
	- available states as a enum list

**Comment by iar5** [comment]
Did a simple storage machine with callback registration. By that all the communication between vue and babylon should be handelt
