### ISSUE TITLE
Getting started w/ docker

### ISSUE THREAD

**Issue by dephiloper** [vi-sense/vi-sense#5]
Research on the basics of how to use docker and a possible use in the project.

**Comment by RomanKrajewski** [comment]
### Docker für vi-sense ### 
Ich würde vorschlagen, dass wir das Backend für vi-sense mit einer Microservice Architektur mithilfe von Docker umsetzen, da das ein Industriestandard ist, den ich gerne lernen würde.

Folgendes würde ich damit gerne umsetzen:
- Multi-Container Dockeranwendung, in der zb die Datenbank und der Webserver seperiert sind
- CI-CD mittels Github Actions
- Deployment auf dem HTW Server

Hierzu habe ich schonmal Artikel rausgesucht, die beschreiben wie man eine Rest API entweder mit [Django](https://docs.docker.com/compose/django/) oder mit [Go](https://medium.com/@yusufkaratoprak/golang-rest-api-by-docker-7ad7d9b05e22) aufsetzt. Hier spiegelt sich wiederum wieder, was ich bereits in #4 geschrieben habe, für den Prozess mit Django gibt es einen offiziellen Artikel in den Docker Docs, wohingegen der Prozess für Go in einem Medium Artikel beschrieben ist, was darauf hindeutet, dass Django besser beschrieben und unterstützt wird.

**Comment by RomanKrajewski** [comment]
done
