### ISSUE TITLE
Implement timeline 

### ISSUE THREAD

**Issue by iar5** [vi-sense/vi-sense#55]
Schnickschnack Ideas
- graph info on hover info https://observablehq.com/@d3/multi-line-chart + hide/highlight sensor in babylon aswell
- graph on click -> camera drive to sensor

Core features
- [x] show multiple graphs on corresponding gui selection
- [x] time selection pin dragable 
- [x] zoom and pan 
- [x] time range selection + coexistence with zoom
- [x] play 
- [x] set time and range from outside
- [x] think about graph units (multiple y axis?, dynamic axis?)
- [x] graph/info pane sensor indication with different color 
- [x] limit pan and data to Date.now()
- [x] dynamisches nachladen on pan/zoom 
- [x] data caching to not have all available data in d3 all the time
- [x] fake load realtime data 
- [x] control icons/elements 
- [x] option pane connection
- [x] show anomalies
- [x] "move to anomaly" functionalioty for history pane
- [ ] deal with missing data 

<h1>Concept</h1>

Features and concept
- select time with pin (select a data point)
- select a time period (dont zoom which is default in most libs) but use it later as a range for playback
- scroll back and forth in time (y axis) (with buttons)
- zoom in (with buttons)
- show multiple graphs
- highlight sections
- realtime update graphs and data

Idea
- since charts are the key feature of the timeline a chart library can be used as a basis
- not too fancy, more scientific?
- use a free to use lib
- https://github.com/zingchart/awesome-charting

Some notes about some chart libs
- D3 (most github stars, very popular)
 	- pretty sick examples/possibilities 
	- low level svg/data modification lib
- chart.js (second most github stars)
	- pretty clean
	- well known 
- apexcharts
	- 8k stars
	- https://github.com/apexcharts/apexcharts.js
	- some nice timeline examples see bottom of readme.md 
	-  more advanced examples at fusioncharts (based on apex but is commercial)
- dygraphs
	- 2,8k stars
	- http://dygraphs.com/gallery/#g/range-selector

I tried apexchart but came to the conclusion that we need a more low-level lib since we need a lot of custom adjustments and modifications for a timeline, as we imagine it. So i will go with D3

Questions/Notes
- werden die sensordaten immer gemeinsam zur selben zeit gemessen? **wahrscheinlich nicht -> zeitpin NICHT auf datenpunkte einrasten lassen, sondern auch dazwischen. wert wird dann interpoliert, muss gekennzeichnet werden!**
- beim play datenpunktne interpolieren für play und pin selection? oder verzögertes springen
- wie graphen mit unterschiedlichen größen in einer chart? (multiple y achsen?)

**Comment by dephiloper** [comment]
visualize multiple data graphs

**Comment by iar5** [comment]
Features
- show time
- select specific time with pin
- select a time period and make it playable in a loop
- update to latest time/values
- update graphs and sensor data

**Comment by iar5** [comment]
Concept
- Select a period: dont zoom in (default in most libs) but use it for playback
- +- buttons to zoom
- buttons to go back and forth in time

**Comment by iar5** [comment]
D3 features we need
- zoom and pan https://observablehq.com/@d3/zoomable-area-chart
- pan bar https://observablehq.com/@d3/pannable-chart
- data point info https://observablehq.com/@d3/line-chart-with-tooltip
- time selector https://observablehq.com/@d3/index-chart
- play button https://observablehq.com/@mbostock/the-wealth-health-of-nations
