### ISSUE TITLE
Sensor Initialisation

### ISSUE THREAD

**Issue by lnlytumbleweed** [vi-sense/vi-sense#74]
The position of the sensor should be set manually of the user. There should also be a way to set gradient/value limits that define anomalies.

- [x] Sketch process

<del>- [ ] Create Initpage in Vue</del>

- [x] Create button in Infopane 'Init Sensor'

- [x] Connect it with a Babylon-SensorInitSelection function

- [x] Connect Treshholds/limits Value and gradient with API and Timline

**Comment by lnlytumbleweed** [comment]
**Sketch process**
Lo-Fi
![Notiz 31 05 2020](https://user-images.githubusercontent.com/26483797/84136570-c99cff80-aa4b-11ea-81b3-ed23fe9a92f7.png)

Hi-Fi
![Sensor_Initalisation](https://user-images.githubusercontent.com/26483797/84136610-d6215800-aa4b-11ea-8ca8-1cee02d7a860.png)

**Comment by RomanKrajewski** [comment]
Wie der User den Gradienten einstellen können sollte: angeben wie weit die temperatur höchstens in 10 min steigen/fallen darf.
