### ISSUE TITLE
Concept + Impl Minimap

### ISSUE THREAD

**Issue by iar5** [vi-sense/vi-sense#77]
Research on a concept for a minimap which should be located on the top right as an overlay of the 3d view.

**Comment by grimmle** [comment]
Example with viewports - good performance, can not be placed outside of main view
https://www.babylonjs-playground.com/#6PA720#147

Example with two canvases - terrible performance
https://www.babylonjs-playground.com/#G1XIAR

**Comment by dephiloper** [comment]
* closed due to time issues
