### ISSUE TITLE
Acquire an amount, that exceeds the minimum of two multiplied with the number of team members, of digital three-dimensional building representations including heating systems that meet our quality expectations.

### ISSUE THREAD

**Issue by iar5** [vi-sense/vi-sense#78]

**Comment by RomanKrajewski** [comment]
[https://www.turbosquid.com/FullPreview/Index.cfm/ID/1032908](https://www.turbosquid.com/FullPreview/Index.cfm/ID/1032908)
Formats: ipt and stp
pretty detailed looking heating system, there is no house around it, but maybe we can put it in some random house we find online.

[https://www.turbosquid.com/3d-models/free-ige-model-heat-house/1032912?referral=3dmdb](https://www.turbosquid.com/3d-models/free-ige-model-heat-house/1032912?referral=3dmdb)
same here - format: iges

[https://www.turbosquid.com/3d-models/free-boiler-house-main-equipment-3d-model/880168](https://www.turbosquid.com/3d-models/free-boiler-house-main-equipment-3d-model/880168)
another heating room - format: 3ds max

**Comment by iar5** [comment]
https://www.turbosquid.com/FullPreview/Index.cfm/ID/1231898

**Comment by lnlytumbleweed** [comment]
https://3dhaupt.com/my-buildings-collection-on-sketchfab/

**Comment by iar5** [comment]
von philipp:
https://www.cgtrader.com/free-3d-models/exterior/industrial/industrial-building--5
https://www.cgtrader.com/free-3d-models/industrial/other/warehouse-interior-and-exterior-whit-props
