### ISSUE TITLE
Create at least three concepts for the User Interface with sketch

### ISSUE THREAD

**Issue by lnlytumbleweed** [vi-sense/vi-sense#8]
- [x] Find out the minimal requirements
- [x] Look at best-practice cases in the field
- [x] Draw low-fi mockups with sketch (at least 3)

**Comment by lnlytumbleweed** [comment]
Find out the minimal requirements:

- The user should be able to choose between the different buildings/models 
- The user should be able to navigate to the sensor(s) of the (heating) system
- The user should understand how the systems (pipes) are connected and which role the element plays they are looking at
- The user should see an issue within the system in a comprehensible way to maintenance it
- The user can control the timespan of the measurement data
- The user should see for each sensor the current values, time series and related sensors

**Comment by lnlytumbleweed** [comment]
Look at best-practice cases in the field

Project Dasher:
https://dasher360.com/share/oVAM3dF7M

![Bildschirmfoto 2020-04-19 um 20 15 20](https://user-images.githubusercontent.com/26483797/79696197-7690a280-827b-11ea-9b3d-c9a43b5208fb.png)

xeogl example:
https://xeogl.org/examples/#camera_path_frameMenu

![Bildschirmfoto 2020-04-21 um 09 15 08](https://user-images.githubusercontent.com/26483797/79836747-db99e480-83b0-11ea-9551-6021440470a6.png)


BIM Visualization Application:
https://www.youtube.com/watch?v=KUIDA_5RZEg

![Bildschirmfoto 2020-04-21 um 09 16 18](https://user-images.githubusercontent.com/26483797/79836770-e0f72f00-83b0-11ea-97d8-27ebd9884c1a.png)

**Comment by lnlytumbleweed** [comment]
Draw low-fi mockups with sketch (at least 3)

Ladingpage:
![Ladingpage HD](https://user-images.githubusercontent.com/26483797/79887698-95b63e00-83fb-11ea-9c4a-a61875437e63.png)

Mockup 1 Xeoglexample:
![BIM Mockup 1 Xeoglexample HD](https://user-images.githubusercontent.com/26483797/79888354-c9459800-83fc-11ea-8ca1-55537e110c90.png)

Mockup 2 Dasherexample:
![BIM Mockup Dasherexample HD](https://user-images.githubusercontent.com/26483797/79887712-9c44b580-83fb-11ea-9dbe-109a79a6e357.png)

Mockup 3 Both:
![BIM Mockup Both HD](https://user-images.githubusercontent.com/26483797/79887722-9f3fa600-83fb-11ea-9ae5-3068f2d090b1.png)

**Comment by lnlytumbleweed** [comment]
Update Minimap:

While I was searching for a UI framework for the frontend, I noticed a pretty cool solution for a **minimap**:

![Bildschirmfoto 2020-04-27 um 12 27 45](https://user-images.githubusercontent.com/26483797/80383156-83c51700-88a3-11ea-9bba-2f25b5016a69.png)

(source: https://www.monterail.com/blog/3d-editor-vue.js-reactive-entity-system)

**Comment by dephiloper** [comment]
I think that is the minimap @RomanKrajewski also suggested. Nonetheless I also think that could be a good realization.
