### ISSUE TITLE
Startpage redesign 

### ISSUE THREAD

**Issue by iar5** [vi-sense/vi-sense#97]
Absprechen mit https://github.com/vi-sense/vi-sense/issues/95

Show model info cards https://vuetifyjs.com/en/components/cards/
Show more information, weather, location/map

- [x] Sketch Startpage @iar5

**Comment by iar5** [comment]
ganz einfacher sketch mit kacheln
geht nur um das grobe layout, das css styling sollte natürlich bisschen schöner aussehen

![startpage](https://user-images.githubusercontent.com/32841473/85022215-48441c00-b173-11ea-9ca4-54d804c9bb12.png)
[startpage.zip](https://github.com/vi-sense/vi-sense/files/4798637/startpage.zip)

**Comment by lnlytumbleweed** [comment]
- [x] Vuetify cards integration

- [x] Leaflet integration

- [x] Anomaly Integration

- [x] Current Weather integration

- [x] Demo Account Dialog pop Up integration!

**Comment by lnlytumbleweed** [comment]
![Bildschirmfoto 2020-07-08 um 20 05 32](https://user-images.githubusercontent.com/26483797/86954594-8cb14f00-c156-11ea-8e86-ebaa6b67c108.png)
